# Generated by Django 2.1.2 on 2018-10-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20181027_2258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hashtags',
            options={'verbose_name': '해시태그', 'verbose_name_plural': '해시태그 목록'},
        ),
        migrations.AddField(
            model_name='comment',
            name='_html',
            field=models.TextField(blank=True, verbose_name='태그가 HTML화된 댓글 내용'),
        ),
    ]
