# Generated by Django 2.1.2 on 2018-10-22 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20181022_1144'),
        ('members', '0004_auto_20181019_1252'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
